name: Delete github packages

on:
  workflow_call:
    inputs:
      package-name:
        description: 'The name of the package to clean.'
        required: true
        type: string
      min-versions-to-keep:
        description: "Number of latest versions to keep (min: 1)"
        required: true
        default: "5"
        type: number
      delete-only-untagged-versions:
        description: "Delete only untagged versions"
        required: true
        default: true
        type: boolean

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ inputs.package-name }}
          package-type: "container"
          min-versions-to-keep: ${{ inputs.min-versions-to-keep }}
          delete-only-pre-release-versions: ${{ inputs.delete-only-untagged-versions }}
